# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "./lanes/PreRelease.rb"
import "./lanes/ReleaseQa.rb"

require 'yaml'

def load_config(environment)
    config_file = File.join(Dir.pwd, "config", "environment_#{environment}.yml")
    YAML.load_file(config_file)
end

default_platform(:android)

platform :android do

    lane :verification do |options|
        buildType = options[:build_type] || "debug"
        clean
        build(build_type: buildType)
        test
        lint
    end

    lane :full_pre_release do
        verification(build_type: "debug")
    end

    lane :full_release_qa do
#         check_qa_branch
#         verification(build_type: "release")
#         increment_version
#         create_release_qa_branch
        push_release_qa_branch(load_config("qa"))
    end
end
