# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "./lanes/Common.rb"
import "./lanes/ReleaseQa.rb"

require 'yaml'

def load_config(environment)
    config_file = File.join(Dir.pwd, "config", "environment_#{environment}.yml")
    YAML.load_file(config_file)
end

default_platform(:android)

platform :android do

    private_lane :verification do |options|
        buildType = options[:build_type] || "debug"
        clean
        build(build_type: buildType)
        test
        lint
    end

    lane :pipeline_pre_release do
        verification(build_type: "debug")
    end

    lane :pipeline_release_qa do
        config = load_config("qa")
        git_url = "https://#{config['git_domain']}/#{config['git_remote']}"
        check_qa_branch(git_remote: git_url)
        verification(build_type: "release")
        version_name_key = "versionName"
        bundle_version_key = "bundleVersion"
        version_name = get_gradle_property(version_name_key, "../gradle.properties")
        bundle_version = get_gradle_property(bundle_version_key, "../gradle.properties")
        increment_version(
            version_name_key: version_name_key,
            bundle_version_key: bundle_version_key,
            version_name: version_name,
            bundle_version: bundle_version
        )
        create_release_qa_branch
        push_release_qa_branch(config)
    end
end
